import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import ResponsiveAppBar from "@/components/ResponsiveAppBar/ResponsiveAppBar";
import HeroSection from "@/pages-sections/hero-section/HeroSection";
import CompetenceSection from "@/pages-sections/competence-section/CompetenceSection";
import PerformanceSection from "@/pages-sections/performance-section/PerformanceSection";
import ExpertSection from "@/pages-sections/expert-section/ExpertSection";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <ResponsiveAppBar />
      <HeroSection />
      <CompetenceSection />
      <PerformanceSection />
      <ExpertSection />
    </>
  );
}
