import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import ResponsiveAppBar from "@/components/ResponsiveAppBar/ResponsiveAppBar";
import HeroSection from "@/pages-sections/hero-section/HeroSection";
import CompetenceSection from "@/pages-sections/competence-section/CompetenceSection";
import PerformanceSection from "@/pages-sections/performance-section/PerformanceSection";
import ExpertSection from "@/pages-sections/expert-section/ExpertSection";
import ToolSection from "@/pages-sections/tool-section/ToolSection";
import CtaSection from "@/pages-sections/cta-section/CtaSection";
import FooterSection from "@/pages-sections/footer-section/FooterSection";
import { useRouter } from "next/router";

import en from "../locales/en";
import de from "../locales/de";
import tr from "../locales/tr";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  const { locale, locales, defaultLocale } = router;
  let t;
  switch (locale) {
    case "en":
      t = en;
      break;
    case "de":
      t = de;
      break;
    case "tr":
      t = tr;
      break;
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <ResponsiveAppBar />
      <HeroSection />
      <CompetenceSection />
      <PerformanceSection />
      <ExpertSection />
      <ToolSection />
      <CtaSection />
      <FooterSection />
    </>
  );
}
